version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.54.0
    container_name: prometheus-bench
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports: ["9090:9090"]

  grafana:
    image: grafana/grafana:11.1.0
    container_name: grafana-bench
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports: ["3000:3000"]

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: pg-exporter-bench
    environment:
      DATA_SOURCE_NAME: "postgresql://bench_user:bench_pass@host.docker.internal:5432/bench_rest?sslmode=disable"
    ports: ["9187:9187"]
