global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'variant-c'
    metrics_path: /actuator/prometheus
    static_configs: [{ targets: ['host.docker.internal:8080'] }]

  # (on ajoutera D et A plus tard)
  - job_name: 'postgres'
    static_configs: [{ targets: ['host.docker.internal:9187'] }]
